name: python3
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - basemap
  - cdo
  - geopy
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pip
  - scipy
  - seaborn
  - pip:
    - netcdf4
