name: python3
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - cartopy
  - cdo=1.9.10
  - cmocean=2.0
  - geoviews
  - ipywidgets=7.6.3
  - jupyterlab=3.0.16
  - matplotlib=3.4.2
  - numpy=1.21.0
  - pandas=1.3.0
  - pip=21.1.3
  - python=3.9.6
  - scipy=1.7.0
  - xarray=0.18.2
  - pip:
    - itables
    - netcdf4
    - seaborn
    - voila
